install:
- npm install
branches:
  only:
  - master
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_script:
- git pull origin master
before_install:
- openssl aes-256-cbc -K $encrypted_cbae5432186b_key -iv $encrypted_cbae5432186b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 118.24.62.205\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- npm run build
- scp -r stricthostkeychecking=no dist/. root@118.24.62.205:/home/test/cherryblog.site
env:
  global:
  - GH_REF: git@github.com:sunshine940326/cherry_management.git
